# Generated by Django 2.0.1 on 2018-04-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_date', models.DateField()),
                ('article_title', models.CharField(max_length=100, verbose_name='Заголовок статьи')),
                ('article_image', models.ImageField(blank=True, upload_to='media')),
                ('article_text', models.TextField(verbose_name='Текст статьи')),
            ],
        ),
    ]
