# Generated by Django 2.0.1 on 2018-06-07 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elbrusblog', '0002_auto_20180422_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateField(default=datetime.date(2018, 6, 7), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст статьи'),
        ),
    ]
