# Generated by Django 2.0.1 on 2018-06-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elbrusblog', '0003_auto_20180607_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateField(verbose_name='Дата события'),
        ),
    ]
