# Generated by Django 2.0.1 on 2018-06-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elbrusblog', '0005_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber_email',
            field=models.EmailField(max_length=254, verbose_name='Email падписчика'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber_message',
            field=models.TextField(verbose_name='Сообщение подписчика'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber_message_date',
            field=models.DateField(auto_now=True, verbose_name='Дата сообщения'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber_name',
            field=models.CharField(max_length=100, verbose_name='Имя подписчика'),
        ),
    ]
